---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider-config
spec:
  assumeRoleWithWebIdentity:
    roleARN: arn:aws:iam::504376484015:role/production-crossplane-config-irsa

  credentials:
    source: InjectedIdentity
