apiVersion: tf.upbound.io/v1beta1 
kind: Workspace
metadata:
  name: production
  annotations:
    # The terraform workspace will be named 'myworkspace'. If you omit this
    # annotation it would be derived from metadata.name - e.g. 'example-remote'.
    crossplane.io/external-name: production
spec:
  providerConfigRef:
    name: aws-irsa
  forProvider:
    # Git based remote module is supported.
    # See https://www.terraform.io/language/modules/sources#generic-git-repository
    # and https://www.terraform.io/language/modules/sources#modules-in-package-sub-directories
    # for URL structure.
    # You can also specify a simple main.tf inline; see
    # workspace-inline.yaml.
    source: Remote
    module: git::https://github.com/autotune/bank-of-anthos.git//aws/crossplane?ref=main
    # Variable files can be loaded from a ConfigMap or a Secret.
    varFiles:
    - source: SecretKey
      secretKeyRef:
        namespace: upbound-system
        name: terraform
        key: production.tfvars
  # All Terraform outputs are written to the connection secret.
  writeConnectionSecretToRef:
    namespace: upbound-system
    name: terraform-boa-prod-remote
