# Default values for EKS cluster config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

applicationName: bsee
persistentVolumeClaim: bsee-pvc2
containerRegistry: "public.ecr.aws"

maxCpuPerContainer: 4000m
minCpuPerContainer: 100m
defaultCpuPerContainer: 100m
defaultRequestCpuPerContainer: 100m

maxMemoryPerContainer: 8Gi
minMemoryPerContainer: 128Mi
defaultMemoryPerContainer: 128Mi
defaultRequestMemoryPerContainer: 128Mi

webServerContainerCpu: 1400m
webServerContainerMemory: 4Gi
enterpriseServerContainerCpu: 1400m
enterpriseServerContainerMemory: 4Gi
connectionCheckContainerCpu: 1400m
connectionCheckContainerMemory: 1Gi
scanContainerCpu: 1400m
scanContainerMemory: 8Gi

services:
  webServer:
    label: "app.portswigger.net/ingress: web-server"
    domainName: "bsee"

support:
  oracle: false
